n = input('Digite algo: ')
tp = type(n)
es = n.isspace()
en = n.isnumeric()
an = n.isalnum()
mai = n.isupper()
minu = n.islower()
#cap
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabetico?', n.isalpha())
print('É alfanumerico?', n.isalnum())
print('Esta em maiusculas?', n.isupper())
print('Esta em minusculas?', n.islower())
print('Esta captalizada?', n.istitle())
